// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUs0TbSxNcW7pOcz2x31-Ty3J3vgVC3FU',
    appId: '1:950754981884:web:c303ff762cda20e45f2479',
    messagingSenderId: '950754981884',
    projectId: 'mlbv2-486f3',
    authDomain: 'mlbv2-486f3.firebaseapp.com',
    storageBucket: 'mlbv2-486f3.appspot.com',
    measurementId: 'G-MLGS8XZZ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABErEkjBEz46ZbaLt4hurnpXbphCEH0-E',
    appId: '1:950754981884:android:45f423dfbac6b6d35f2479',
    messagingSenderId: '950754981884',
    projectId: 'mlbv2-486f3',
    storageBucket: 'mlbv2-486f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKgYJJCFoMKd8nOWybdpWpWNMhmu9bfM',
    appId: '1:950754981884:ios:ed106cb8225684eb5f2479',
    messagingSenderId: '950754981884',
    projectId: 'mlbv2-486f3',
    storageBucket: 'mlbv2-486f3.appspot.com',
    iosClientId: '950754981884-vho7vdgchtlmfakf29v390nkumqc8qvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myloanbhai',
  );
}
